# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:

        AppBundle\Entity\User: bcrypt

    providers:

        database_users:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        secured_area:

            pattern: ^/

            anonymous: true

            # This allows the user to login by submitting a username and password
            # Reference: http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:

                check_path: blog_login

                login_path: blog_login

                csrf_token_generator: security.csrf.token_manager
                
                default_target_path: admin_index

            logout:
                # The route name the user can go to in order to logout
                path: blog_logout
                # The name of the route to redirect to after logging out
                target: blog_home

    access_control:

        - { path: '^/admin', roles: ROLE_ADMIN }
