# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: AppBundle\Utils\Slugger

    app.form.type.tag:
        class: AppBundle\Form\TagType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
